Map<String, List<Map<String, dynamic>>> a = {
  "relations": [
    {
      "originTagIds": [11],
      "destinationTagId": 10,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [34],
      "destinationTagId": 33,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [35],
      "destinationTagId": 33,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [36],
      "destinationTagId": 33,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [37],
      "destinationTagId": 33,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [49],
      "destinationTagId": 48,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [53],
      "destinationTagId": 52,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [54],
      "destinationTagId": 52,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [55],
      "destinationTagId": 52,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [63],
      "destinationTagId": 62,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [81],
      "destinationTagId": 80,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [82],
      "destinationTagId": 80,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [83],
      "destinationTagId": 80,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [84],
      "destinationTagId": 80,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [87],
      "destinationTagId": 86,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [103],
      "destinationTagId": 102,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [104],
      "destinationTagId": 102,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [105],
      "destinationTagId": 102,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [156],
      "destinationTagId": 155,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [208],
      "destinationTagId": 207,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [216],
      "destinationTagId": 215,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [217],
      "destinationTagId": 215,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [218],
      "destinationTagId": 215,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [219],
      "destinationTagId": 215,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [221],
      "destinationTagId": 220,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [225],
      "destinationTagId": 224,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [226],
      "destinationTagId": 224,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [260],
      "destinationTagId": 259,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [261],
      "destinationTagId": 259,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [262],
      "destinationTagId": 259,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [339],
      "destinationTagId": 338,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [356],
      "destinationTagId": 355,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [384],
      "destinationTagId": 383,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [385],
      "destinationTagId": 383,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [412],
      "destinationTagId": 411,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [464],
      "destinationTagId": 463,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [469],
      "destinationTagId": 468,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [470],
      "destinationTagId": 468,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [471],
      "destinationTagId": 468,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [472],
      "destinationTagId": 468,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [473],
      "destinationTagId": 468,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [531],
      "destinationTagId": 530,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [532],
      "destinationTagId": 530,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [548],
      "destinationTagId": 547,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [549],
      "destinationTagId": 547,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [550],
      "destinationTagId": 547,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [551],
      "destinationTagId": 547,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [552],
      "destinationTagId": 547,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [553],
      "destinationTagId": 547,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [555],
      "destinationTagId": 554,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [556],
      "destinationTagId": 554,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [557],
      "destinationTagId": 554,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [558],
      "destinationTagId": 554,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [561],
      "destinationTagId": 560,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [562],
      "destinationTagId": 560,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [563],
      "destinationTagId": 560,
      "relation": {"type": "synonym"}
    },
    {
      "originTagIds": [564],
      "destinationTagId": 560,
      "relation": {"type": "synonym"}
    }
  ],
  "tags": [
    {"tagName": "Pivo", "tagId": 0, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hospoda", "tagId": 1, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Outdoor", "tagId": 2, "tagType": 3, "lang": "cz", "authorId": -1},
    {"tagName": "Alkohol", "tagId": 3, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Magic: the gathering", "tagId": 4, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Larp", "tagId": 5, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Nekuřácká akce", "tagId": 6, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Divadlo", "tagId": 7, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Indoor", "tagId": 8, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Opera", "tagId": 9, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Deskovky", "tagId": 10, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Deskové hry", "tagId": 11, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Muzeum", "tagId": 12, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sport", "tagId": 13, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Počítač", "tagId": 14, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Technologie", "tagId": 15, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hala", "tagId": 16, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tělocvična", "tagId": 17, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hřiště", "tagId": 18, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Voda", "tagId": 19, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Řeka", "tagId": 20, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rybník", "tagId": 21, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Jezero", "tagId": 22, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Skála", "tagId": 23, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Výšlap", "tagId": 24, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hudba", "tagId": 25, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zvířata", "tagId": 26, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Les", "tagId": 27, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rock", "tagId": 28, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Jídlo", "tagId": 29, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Metal", "tagId": 30, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Punk", "tagId": 31, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kino", "tagId": 32, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Město", "tagId": 33, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ostrava", "tagId": 34, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Praha", "tagId": 35, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Brno", "tagId": 36, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Olomouc", "tagId": 37, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Křesťanství", "tagId": 38, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vánoce", "tagId": 39, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vzdělávání", "tagId": 40, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Maso", "tagId": 41, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Děti", "tagId": 42, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Akce pro děti", "tagId": 43, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Islám", "tagId": 44, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tábor", "tagId": 45, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Historie", "tagId": 46, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hrady", "tagId": 47, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Památky", "tagId": 48, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Unesco", "tagId": 49, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Hory", "tagId": 50, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Park", "tagId": 51, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tvrdý alkohol", "tagId": 52, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Režná", "tagId": 53, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Vodka", "tagId": 54, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Rum", "tagId": 55, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Demonstrace", "tagId": 56, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Cyklistika", "tagId": 57, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Věda", "tagId": 58, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Apple", "tagId": 59, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Geocache", "tagId": 60, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bezalkoolová", "tagId": 61, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Festival", "tagId": 62, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hudební festival", "tagId": 63, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Keltský", "tagId": 64, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Umění", "tagId": 65, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Létání", "tagId": 66, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tanec", "tagId": 67, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Limonáda", "tagId": 68, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kopec", "tagId": 69, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rozhledna", "tagId": 70, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Výstava", "tagId": 71, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Film", "tagId": 72, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bitva", "tagId": 73, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dospělí", "tagId": 74, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Poker", "tagId": 75, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lanka", "tagId": 76, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Řemesla", "tagId": 77, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sraz", "tagId": 78, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Středověk", "tagId": 79, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Fantasy", "tagId": 80, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Troll", "tagId": 81, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Mág", "tagId": 82, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Špičatý klobouk", "tagId": 83, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Trpaslíci", "tagId": 84, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Výlet", "tagId": 85, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vojenské", "tagId": 86, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Armáda", "tagId": 87, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Déšť", "tagId": 88, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Slunce", "tagId": 89, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sníh", "tagId": 90, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mráz", "tagId": 91, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vlak", "tagId": 92, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Oslava", "tagId": 93, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dřevárna", "tagId": 94, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zámek", "tagId": 95, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hrad", "tagId": 96, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zoo", "tagId": 97, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Jóga", "tagId": 98, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Cvičení", "tagId": 99, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Brigáda", "tagId": 100, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Workout", "tagId": 101, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Wod", "tagId": 102, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Upír", "tagId": 103, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Upírka", "tagId": 104, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Upíři", "tagId": 105, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Noc", "tagId": 106, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Den", "tagId": 107, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Omg", "tagId": 108, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Prohlídka", "tagId": 109, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Víno", "tagId": 110, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Programování", "tagId": 111, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Myslivost", "tagId": 112, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Flóra", "tagId": 113, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Válka", "tagId": 114, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Auto", "tagId": 115, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Auta", "tagId": 116, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Senoseč", "tagId": 117, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Trnkobraní", "tagId": 118, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Baroko", "tagId": 119, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vinobraní", "tagId": 120, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Renesance", "tagId": 121, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Gotika", "tagId": 122, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Koncert", "tagId": 123, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Starověk", "tagId": 124, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Velká morava", "tagId": 125, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Humanismus", "tagId": 126, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Baterka", "tagId": 127, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Jeskyně", "tagId": 128, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Filozofie", "tagId": 129, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Louč", "tagId": 130, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Psychologie", "tagId": 131, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Oheň", "tagId": 132, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Táborák", "tagId": 133, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Malby", "tagId": 134, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kresby", "tagId": 135, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Příměstský", "tagId": 136, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sochy", "tagId": 137, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Španělsko", "tagId": 138, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Řecko", "tagId": 139, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Irsko", "tagId": 140, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Balkán", "tagId": 141, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vikingové", "tagId": 142, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mayové", "tagId": 143, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Inkové", "tagId": 144, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Král", "tagId": 145, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Aztékové", "tagId": 146, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Nemocnice", "tagId": 147, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Betlém", "tagId": 148, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Osel", "tagId": 149, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bylinky", "tagId": 150, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bor", "tagId": 151, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hvězdy", "tagId": 152, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Víla", "tagId": 153, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Farma", "tagId": 154, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Trh", "tagId": 155, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Jarmark", "tagId": 156, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Pouť", "tagId": 157, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pantonima", "tagId": 158, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Princ", "tagId": 159, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Amerika", "tagId": 160, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Evropa", "tagId": 161, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Labyrint", "tagId": 162, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Antarktida", "tagId": 163, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Karetní hry", "tagId": 164, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Arktida", "tagId": 165, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Skyrim", "tagId": 166, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kostým", "tagId": 167, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Atlantida", "tagId": 168, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pramen", "tagId": 169, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Studánka", "tagId": 170, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Klášter", "tagId": 171, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kostel", "tagId": 172, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ulička", "tagId": 173, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Uličky", "tagId": 174, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kašna", "tagId": 175, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Horolezectví", "tagId": 176, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ekumenické", "tagId": 177, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Poutní místo", "tagId": 178, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pověst", "tagId": 179, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ledovec", "tagId": 180, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Malba", "tagId": 181, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lukostřelba", "tagId": 182, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kaple", "tagId": 183, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Šerm", "tagId": 184, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Jazyk", "tagId": 185, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Venkov", "tagId": 186, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rybářství", "tagId": 187, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kanoe", "tagId": 188, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Klaun", "tagId": 189, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Cirkus", "tagId": 190, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vodáctví", "tagId": 191, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kejklíř", "tagId": 192, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Indiáni", "tagId": 193, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zabíjačka", "tagId": 194, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Krasojezdkyně", "tagId": 195, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Táboření", "tagId": 196, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zážitkovka", "tagId": 197, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kemp", "tagId": 198, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mažoretky", "tagId": 199, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hody", "tagId": 200, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Metro", "tagId": 201, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Posvícení", "tagId": 202, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sklep", "tagId": 203, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tramvaj", "tagId": 204, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sklípek", "tagId": 205, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Šifrovačka", "tagId": 206, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Koupaliště", "tagId": 207, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bazén", "tagId": 208, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Extremismus", "tagId": 209, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Imigranti", "tagId": 210, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zahrádka", "tagId": 211, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pěstitelství", "tagId": 212, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Psi", "tagId": 213, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kočky", "tagId": 214, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zvířátka", "tagId": 215, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Morčata", "tagId": 216, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Fauna", "tagId": 217, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Plazi", "tagId": 218, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Žába", "tagId": 219, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Ptáci", "tagId": 220, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kuřátka", "tagId": 221, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Internet", "tagId": 222, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vaření", "tagId": 223, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Stavebnice", "tagId": 224, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Cheva", "tagId": 225, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Merkur", "tagId": 226, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Koupání", "tagId": 227, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mlýn", "tagId": 228, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Slavnost", "tagId": 229, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pohřeb", "tagId": 230, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hrášek", "tagId": 231, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Židi", "tagId": 232, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Inkvizice", "tagId": 233, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Technika", "tagId": 234, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Boty", "tagId": 235, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Oblečení", "tagId": 236, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Móda", "tagId": 237, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lasergame", "tagId": 238, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lynčování", "tagId": 239, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lego", "tagId": 240, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kostnice", "tagId": 241, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zájezd", "tagId": 242, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Moře", "tagId": 243, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sklo", "tagId": 244, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Keramika", "tagId": 245, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kování", "tagId": 246, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Měď", "tagId": 247, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bronz", "tagId": 248, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Železo", "tagId": 249, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Uhlí", "tagId": 250, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Důl", "tagId": 251, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ropa", "tagId": 252, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sůl", "tagId": 253, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Loď", "tagId": 254, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Magnet", "tagId": 255, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Piráti", "tagId": 256, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Standup komedie", "tagId": 257, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zlato", "tagId": 258, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Šití", "tagId": 259, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Len", "tagId": 260, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Netex", "tagId": 261, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Plátno", "tagId": 262, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Platina", "tagId": 263, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Šaty", "tagId": 264, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Aktinium", "tagId": 265, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Chemie", "tagId": 266, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kouzla", "tagId": 267, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Politika", "tagId": 268, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Guláš", "tagId": 269, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Komunismus", "tagId": 270, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kapitalismus", "tagId": 271, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hackathon", "tagId": 272, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Anglie", "tagId": 273, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Maraton", "tagId": 274, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Morava", "tagId": 275, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bunkr", "tagId": 276, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Prales", "tagId": 277, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Poušť", "tagId": 278, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Škola", "tagId": 279, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Školka", "tagId": 280, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Gymnázium", "tagId": 281, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pochod", "tagId": 282, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ekologie", "tagId": 283, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ekonomie", "tagId": 284, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mykologie", "tagId": 285, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zahrada", "tagId": 286, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Skleník", "tagId": 287, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lopata", "tagId": 288, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Výkop", "tagId": 289, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Přehlídka", "tagId": 290, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Úklid", "tagId": 291, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Cestopis", "tagId": 292, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Elektrárna", "tagId": 293, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Piknik", "tagId": 294, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Práce", "tagId": 295, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Teplárna", "tagId": 296, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pivovar", "tagId": 297, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Masáž", "tagId": 298, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lázně", "tagId": 299, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Termály", "tagId": 300, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Wellness", "tagId": 301, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pláž", "tagId": 302, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Slunění", "tagId": 303, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sauna", "tagId": 304, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Anime", "tagId": 305, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tenis", "tagId": 306, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hokej", "tagId": 307, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Floorball", "tagId": 308, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Víkend", "tagId": 309, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Solná jeskyně", "tagId": 310, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Týpí", "tagId": 311, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Stan", "tagId": 312, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Stanování", "tagId": 313, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pohorky", "tagId": 314, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Furry", "tagId": 315, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Strašidla", "tagId": 316, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Volejbal", "tagId": 317, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Koště", "tagId": 318, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Přehrada", "tagId": 319, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hasiči", "tagId": 320, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Večerníček", "tagId": 321, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Soutěž krásy", "tagId": 322, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vinice", "tagId": 323, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Příroda", "tagId": 324, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vodopád", "tagId": 325, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kameny", "tagId": 326, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Chmelobraní", "tagId": 327, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sci-fi", "tagId": 328, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Chata", "tagId": 329, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Golf", "tagId": 330, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Chalupa", "tagId": 331, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Inline", "tagId": 332, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Byt", "tagId": 333, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Liberec", "tagId": 334, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pára", "tagId": 335, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Parní stroj", "tagId": 336, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zážitek", "tagId": 337, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Adrenalin", "tagId": 338, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vzrušení", "tagId": 339, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Skoba", "tagId": 340, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Extáze", "tagId": 341, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hra", "tagId": 342, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Cyklobus", "tagId": 343, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lanovka", "tagId": 344, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Koloběžky", "tagId": 345, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Skanzen", "tagId": 346, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Techno", "tagId": 347, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dnb", "tagId": 348, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Věž", "tagId": 349, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rnb", "tagId": 350, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dračí doupě", "tagId": 351, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dubstep", "tagId": 352, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Společenské hry", "tagId": 353, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ples", "tagId": 354, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zábava", "tagId": 355, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Čoch", "tagId": 356, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Diskotéka", "tagId": 357, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bál", "tagId": 358, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Paintball", "tagId": 359, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Laser", "tagId": 360, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Laser game", "tagId": 361, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Motokáry", "tagId": 362, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hacker", "tagId": 363, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Google", "tagId": 364, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Microsoft", "tagId": 365, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Včela", "tagId": 366, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Panna", "tagId": 367, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Chrám", "tagId": 368, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Citadela", "tagId": 369, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Svatba", "tagId": 370, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rodinná oslava", "tagId": 371, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Seriály", "tagId": 372, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Cadillac", "tagId": 373, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Star trek", "tagId": 374, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dinosaurus", "tagId": 375, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Game of thrones", "tagId": 376, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zaklínač", "tagId": 377, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Housle", "tagId": 378, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Varhany", "tagId": 379, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mše", "tagId": 380, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kost", "tagId": 381, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kukuřice", "tagId": 382, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Šelma", "tagId": 383, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lev", "tagId": 384, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Tygr", "tagId": 385, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Dravec", "tagId": 386, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kaktusy", "tagId": 387, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dovednost", "tagId": 388, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zeď", "tagId": 389, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sekera", "tagId": 390, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Trabant", "tagId": 391, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lesnictví", "tagId": 392, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Veteráni", "tagId": 393, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dřevorubectví", "tagId": 394, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Fotografování", "tagId": 395, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Východ", "tagId": 396, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Orient", "tagId": 397, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Indie", "tagId": 398, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tibet", "tagId": 399, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Čína", "tagId": 400, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rusko", "tagId": 401, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sibiř", "tagId": 402, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Terminátor", "tagId": 403, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Lindemann", "tagId": 404, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Radar", "tagId": 405, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Saň", "tagId": 406, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mash", "tagId": 407, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Facebook skupina \"jsi holka? přidej se.\"", "tagId": 408, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pár pařmenů", "tagId": 409, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rytíř", "tagId": 410, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kofola", "tagId": 411, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Fofola", "tagId": 412, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Kokain", "tagId": 413, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hifi věž", "tagId": 414, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pán prstenů", "tagId": 415, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zakažte akčník", "tagId": 416, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Battlestar galactica", "tagId": 417, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rally", "tagId": 418, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Voleyball", "tagId": 419, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Beach", "tagId": 420, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Borůvky", "tagId": 421, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bažantrikulace", "tagId": 422, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Konec světa", "tagId": 423, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Konspirace", "tagId": 424, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Špioni", "tagId": 425, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vesmír", "tagId": 426, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Anarchismus", "tagId": 427, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Squat", "tagId": 428, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Jupiter", "tagId": 429, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Káva", "tagId": 430, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Čaj", "tagId": 431, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dýmka", "tagId": 432, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Humbuk", "tagId": 433, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Happening", "tagId": 434, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kratochvíle", "tagId": 435, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kniha", "tagId": 436, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Protest", "tagId": 437, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Svitek", "tagId": 438, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pergamen", "tagId": 439, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Papyrus", "tagId": 440, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Den země", "tagId": 441, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kytara", "tagId": 442, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Řezbář", "tagId": 443, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Svíce", "tagId": 444, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Šňupání", "tagId": 445, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ping pong", "tagId": 446, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Loutka", "tagId": 447, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Loutky", "tagId": 448, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Open-air", "tagId": 449, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pro dospělé", "tagId": 450, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pro děti", "tagId": 451, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pro rodiče s dětmi", "tagId": 452, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Občerstvení", "tagId": 453, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vnitřní", "tagId": 454, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Společenské oblečení", "tagId": 455, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Instrumentální", "tagId": 456, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vokální", "tagId": 457, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Commedia dell'arte", "tagId": 458, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Komedie", "tagId": 459, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Drama", "tagId": 460, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Parodie", "tagId": 461, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dobrodružný film", "tagId": 462, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Western", "tagId": 463, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kovbojka", "tagId": 464, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Historický film", "tagId": 465, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Životopisný film", "tagId": 466, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hudební film", "tagId": 467, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pohádka", "tagId": 468, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Drak", "tagId": 469, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Princezna", "tagId": 470, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Obr", "tagId": 471, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Čarodějnice", "tagId": 472, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Dračice", "tagId": 473, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Láska", "tagId": 474, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Raut", "tagId": 475, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Obrazy", "tagId": 476, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Architektura", "tagId": 477, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Fotografie", "tagId": 478, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Řemeslo", "tagId": 479, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Románský sloh", "tagId": 480, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Gotický sloh", "tagId": 481, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Novověk", "tagId": 482, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Rokoko", "tagId": 483, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Klasicismus", "tagId": 484, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Romantismus", "tagId": 485, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Realismus", "tagId": 486, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Impresionismus", "tagId": 487, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Symbolismus", "tagId": 488, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Secese", "tagId": 489, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Art deco", "tagId": 490, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dadaismus", "tagId": 491, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Funkcionalismus", "tagId": 492, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Surrealismus", "tagId": 493, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vstupné dobrovolné", "tagId": 494, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Sportovní akce", "tagId": 495, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Relaxační", "tagId": 496, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Adrenalinový", "tagId": 497, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Letní", "tagId": 498, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Zimní", "tagId": 499, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kolektivní", "tagId": 500, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Orientační", "tagId": 501, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vodní", "tagId": 502, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Míčový", "tagId": 503, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Bojová umění", "tagId": 504, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Silový", "tagId": 505, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Motorismus", "tagId": 506, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tanced", "tagId": 507, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Turistický", "tagId": 508, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Fandění", "tagId": 509, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "První liga", "tagId": 510, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Druhá liga", "tagId": 511, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Extraliga", "tagId": 512, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mládež", "tagId": 513, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Závod", "tagId": 514, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mírný terén", "tagId": 515, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Střední terén", "tagId": 516, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Náročný terén", "tagId": 517, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ceny pro vítěze", "tagId": 518, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Uzavřená akce", "tagId": 519, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Třídní sraz", "tagId": 520, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pracovní schůzka", "tagId": 521, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Firemní akce", "tagId": 522, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Den otevřených dveří", "tagId": 523, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Tuning", "tagId": 524, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Letecký den", "tagId": 525, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Farmářský trh", "tagId": 526, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Blues", "tagId": 527, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Country", "tagId": 528, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Disco", "tagId": 529, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dechová hudba", "tagId": 530, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Dechovka", "tagId": 531, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Eva a vašek", "tagId": 532, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Duchovní hudba", "tagId": 533, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Elektronická hudba", "tagId": 534, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Folk", "tagId": 535, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Funk", "tagId": 536, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Hip hop", "tagId": 537, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Jazz", "tagId": 538, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Pop", "tagId": 539, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Reggae", "tagId": 540, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "R&b", "tagId": 541, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ska", "tagId": 542, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Underground", "tagId": 543, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Vážná hudba", "tagId": 544, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "World music", "tagId": 545, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Epická hudba", "tagId": 546, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Středověké zbraně", "tagId": 547, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Meč", "tagId": 548, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Luk", "tagId": 549, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Zbroj", "tagId": 550, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Štít", "tagId": 551, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Šíp", "tagId": 552, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Katapult", "tagId": 553, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Počítačové hry", "tagId": 554, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Ork", "tagId": 555, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Warcraft", "tagId": 556, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Wot", "tagId": 557, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Minecraft", "tagId": 558, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Nealko", "tagId": 559, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Kapely", "tagId": 560, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Nightwish", "tagId": 561, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Rammstein", "tagId": 562, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Asonance", "tagId": 563, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Horkýže", "tagId": 564, "tagType": 1, "lang": "cz", "authorId": -1},
    {"tagName": "Násilí", "tagId": 565, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Erotika", "tagId": 566, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Mystika", "tagId": 567, "tagType": 2, "lang": "cz", "authorId": -1},
    {"tagName": "Párty", "tagId": 568, "tagType": 2, "lang": "cz", "authorId": -1}
  ]
};
